<?xml version="1.0" encoding="utf-8"?><Database Name="AssessmentSystem" Class="AssessmentSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOVE;Initial Catalog=AssessmentSystem;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AssessmentSystem" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StdDevelopment" Member="StdDevelopments">
    <Type Name="StdDevelopment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommitteeProject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommitteeRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvisorStdProject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvisorStdRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdvisorClubProject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvisorClubRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DurationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Administrative" Member="Administratives">
    <Type Name="Administrative">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Chancellor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ViceChancellor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Dean" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChancellorAssistant" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ViceDean" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DepartmentHead" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeanOfficeHead" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DeanAssistant" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BranchHeadDirect" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ViceDepartment" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BranchHeadIn" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FacultyCouncilChief" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ViceFactCouncilChief" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Councillors" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Secretary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FacultyBoard" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BranchBoardCmd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchBoardRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AssignmentCmd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignmentRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DurationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AcademicService" Member="AcademicServices">
    <Type Name="AcademicService">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommitteeProject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommitteeRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExpertInHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpertInRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExpertInPracHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpertInPracRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExpertOutHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpertOutRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExpertOutPracHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpertOutPracRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CommitteeAcPerson" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommitteeAcRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CommitteeCrPerson" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommitteeCrRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CommitteeBsPerson" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommitteeBsRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CommitteeThPerson" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommitteeThRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ServiceAnalysisTimes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ServiceAnalysisRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ServiceOtherTimes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ServiceOtherRefer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DurationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Research" Member="Researches">
    <Type Name="Research">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ResName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="RoundID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Refer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProfessorStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Percentage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DurationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supervision" Member="Supervisions">
    <Type Name="Supervision">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StdNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Refer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DurationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>