#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AssessmentSystem")]
	public partial class AssessmentSystemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStdDevelopment(StdDevelopment instance);
    partial void UpdateStdDevelopment(StdDevelopment instance);
    partial void DeleteStdDevelopment(StdDevelopment instance);
    partial void InsertAdministrative(Administrative instance);
    partial void UpdateAdministrative(Administrative instance);
    partial void DeleteAdministrative(Administrative instance);
    partial void InsertAcademicService(AcademicService instance);
    partial void UpdateAcademicService(AcademicService instance);
    partial void DeleteAcademicService(AcademicService instance);
    partial void InsertResearch(Research instance);
    partial void UpdateResearch(Research instance);
    partial void DeleteResearch(Research instance);
    partial void InsertSupervision(Supervision instance);
    partial void UpdateSupervision(Supervision instance);
    partial void DeleteSupervision(Supervision instance);
    #endregion
		
		public AssessmentSystemDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AssessmentSystem"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AssessmentSystemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssessmentSystemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssessmentSystemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AssessmentSystemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StdDevelopment> StdDevelopments
		{
			get
			{
				return this.GetTable<StdDevelopment>();
			}
		}
		
		public System.Data.Linq.Table<Administrative> Administratives
		{
			get
			{
				return this.GetTable<Administrative>();
			}
		}
		
		public System.Data.Linq.Table<AcademicService> AcademicServices
		{
			get
			{
				return this.GetTable<AcademicService>();
			}
		}
		
		public System.Data.Linq.Table<Research> Researches
		{
			get
			{
				return this.GetTable<Research>();
			}
		}
		
		public System.Data.Linq.Table<Supervision> Supervisions
		{
			get
			{
				return this.GetTable<Supervision>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StdDevelopment")]
	public partial class StdDevelopment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _CommitteeProject;
		
		private string _CommitteeRefer;
		
		private System.Nullable<int> _AdvisorStdProject;
		
		private string _AdvisorStdRefer;
		
		private System.Nullable<int> _AdvisorClubProject;
		
		private string _AdvisorClubRefer;
		
		private string _UserName;
		
		private System.Nullable<int> _DurationID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCommitteeProjectChanging(System.Nullable<int> value);
    partial void OnCommitteeProjectChanged();
    partial void OnCommitteeReferChanging(string value);
    partial void OnCommitteeReferChanged();
    partial void OnAdvisorStdProjectChanging(System.Nullable<int> value);
    partial void OnAdvisorStdProjectChanged();
    partial void OnAdvisorStdReferChanging(string value);
    partial void OnAdvisorStdReferChanged();
    partial void OnAdvisorClubProjectChanging(System.Nullable<int> value);
    partial void OnAdvisorClubProjectChanged();
    partial void OnAdvisorClubReferChanging(string value);
    partial void OnAdvisorClubReferChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnDurationIDChanging(System.Nullable<int> value);
    partial void OnDurationIDChanged();
    #endregion
		
		public StdDevelopment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeProject", DbType="Int")]
		public System.Nullable<int> CommitteeProject
		{
			get
			{
				return this._CommitteeProject;
			}
			set
			{
				if ((this._CommitteeProject != value))
				{
					this.OnCommitteeProjectChanging(value);
					this.SendPropertyChanging();
					this._CommitteeProject = value;
					this.SendPropertyChanged("CommitteeProject");
					this.OnCommitteeProjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeRefer", DbType="NVarChar(MAX)")]
		public string CommitteeRefer
		{
			get
			{
				return this._CommitteeRefer;
			}
			set
			{
				if ((this._CommitteeRefer != value))
				{
					this.OnCommitteeReferChanging(value);
					this.SendPropertyChanging();
					this._CommitteeRefer = value;
					this.SendPropertyChanged("CommitteeRefer");
					this.OnCommitteeReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvisorStdProject", DbType="Int")]
		public System.Nullable<int> AdvisorStdProject
		{
			get
			{
				return this._AdvisorStdProject;
			}
			set
			{
				if ((this._AdvisorStdProject != value))
				{
					this.OnAdvisorStdProjectChanging(value);
					this.SendPropertyChanging();
					this._AdvisorStdProject = value;
					this.SendPropertyChanged("AdvisorStdProject");
					this.OnAdvisorStdProjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvisorStdRefer", DbType="NVarChar(MAX)")]
		public string AdvisorStdRefer
		{
			get
			{
				return this._AdvisorStdRefer;
			}
			set
			{
				if ((this._AdvisorStdRefer != value))
				{
					this.OnAdvisorStdReferChanging(value);
					this.SendPropertyChanging();
					this._AdvisorStdRefer = value;
					this.SendPropertyChanged("AdvisorStdRefer");
					this.OnAdvisorStdReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvisorClubProject", DbType="Int")]
		public System.Nullable<int> AdvisorClubProject
		{
			get
			{
				return this._AdvisorClubProject;
			}
			set
			{
				if ((this._AdvisorClubProject != value))
				{
					this.OnAdvisorClubProjectChanging(value);
					this.SendPropertyChanging();
					this._AdvisorClubProject = value;
					this.SendPropertyChanged("AdvisorClubProject");
					this.OnAdvisorClubProjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvisorClubRefer", DbType="NVarChar(MAX)")]
		public string AdvisorClubRefer
		{
			get
			{
				return this._AdvisorClubRefer;
			}
			set
			{
				if ((this._AdvisorClubRefer != value))
				{
					this.OnAdvisorClubReferChanging(value);
					this.SendPropertyChanging();
					this._AdvisorClubRefer = value;
					this.SendPropertyChanged("AdvisorClubRefer");
					this.OnAdvisorClubReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurationID", DbType="Int")]
		public System.Nullable<int> DurationID
		{
			get
			{
				return this._DurationID;
			}
			set
			{
				if ((this._DurationID != value))
				{
					this.OnDurationIDChanging(value);
					this.SendPropertyChanging();
					this._DurationID = value;
					this.SendPropertyChanged("DurationID");
					this.OnDurationIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrative")]
	public partial class Administrative : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<bool> _Chancellor;
		
		private System.Nullable<bool> _ViceChancellor;
		
		private System.Nullable<bool> _Dean;
		
		private System.Nullable<bool> _ChancellorAssistant;
		
		private System.Nullable<bool> _ViceDean;
		
		private System.Nullable<bool> _DepartmentHead;
		
		private System.Nullable<bool> _DeanOfficeHead;
		
		private System.Nullable<bool> _DeanAssistant;
		
		private System.Nullable<bool> _BranchHeadDirect;
		
		private System.Nullable<bool> _ViceDepartment;
		
		private System.Nullable<bool> _BranchHeadIn;
		
		private System.Nullable<bool> _FacultyCouncilChief;
		
		private System.Nullable<bool> _ViceFactCouncilChief;
		
		private System.Nullable<bool> _Councillors;
		
		private System.Nullable<bool> _Secretary;
		
		private System.Nullable<bool> _FacultyBoard;
		
		private System.Nullable<int> _BranchBoardCmd;
		
		private string _BranchBoardRefer;
		
		private System.Nullable<int> _AssignmentCmd;
		
		private string _AssignmentRefer;
		
		private string _UserName;
		
		private System.Nullable<int> _DurationID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnChancellorChanging(System.Nullable<bool> value);
    partial void OnChancellorChanged();
    partial void OnViceChancellorChanging(System.Nullable<bool> value);
    partial void OnViceChancellorChanged();
    partial void OnDeanChanging(System.Nullable<bool> value);
    partial void OnDeanChanged();
    partial void OnChancellorAssistantChanging(System.Nullable<bool> value);
    partial void OnChancellorAssistantChanged();
    partial void OnViceDeanChanging(System.Nullable<bool> value);
    partial void OnViceDeanChanged();
    partial void OnDepartmentHeadChanging(System.Nullable<bool> value);
    partial void OnDepartmentHeadChanged();
    partial void OnDeanOfficeHeadChanging(System.Nullable<bool> value);
    partial void OnDeanOfficeHeadChanged();
    partial void OnDeanAssistantChanging(System.Nullable<bool> value);
    partial void OnDeanAssistantChanged();
    partial void OnBranchHeadDirectChanging(System.Nullable<bool> value);
    partial void OnBranchHeadDirectChanged();
    partial void OnViceDepartmentChanging(System.Nullable<bool> value);
    partial void OnViceDepartmentChanged();
    partial void OnBranchHeadInChanging(System.Nullable<bool> value);
    partial void OnBranchHeadInChanged();
    partial void OnFacultyCouncilChiefChanging(System.Nullable<bool> value);
    partial void OnFacultyCouncilChiefChanged();
    partial void OnViceFactCouncilChiefChanging(System.Nullable<bool> value);
    partial void OnViceFactCouncilChiefChanged();
    partial void OnCouncillorsChanging(System.Nullable<bool> value);
    partial void OnCouncillorsChanged();
    partial void OnSecretaryChanging(System.Nullable<bool> value);
    partial void OnSecretaryChanged();
    partial void OnFacultyBoardChanging(System.Nullable<bool> value);
    partial void OnFacultyBoardChanged();
    partial void OnBranchBoardCmdChanging(System.Nullable<int> value);
    partial void OnBranchBoardCmdChanged();
    partial void OnBranchBoardReferChanging(string value);
    partial void OnBranchBoardReferChanged();
    partial void OnAssignmentCmdChanging(System.Nullable<int> value);
    partial void OnAssignmentCmdChanged();
    partial void OnAssignmentReferChanging(string value);
    partial void OnAssignmentReferChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnDurationIDChanging(System.Nullable<int> value);
    partial void OnDurationIDChanged();
    #endregion
		
		public Administrative()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chancellor", DbType="Bit")]
		public System.Nullable<bool> Chancellor
		{
			get
			{
				return this._Chancellor;
			}
			set
			{
				if ((this._Chancellor != value))
				{
					this.OnChancellorChanging(value);
					this.SendPropertyChanging();
					this._Chancellor = value;
					this.SendPropertyChanged("Chancellor");
					this.OnChancellorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViceChancellor", DbType="Bit")]
		public System.Nullable<bool> ViceChancellor
		{
			get
			{
				return this._ViceChancellor;
			}
			set
			{
				if ((this._ViceChancellor != value))
				{
					this.OnViceChancellorChanging(value);
					this.SendPropertyChanging();
					this._ViceChancellor = value;
					this.SendPropertyChanged("ViceChancellor");
					this.OnViceChancellorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dean", DbType="Bit")]
		public System.Nullable<bool> Dean
		{
			get
			{
				return this._Dean;
			}
			set
			{
				if ((this._Dean != value))
				{
					this.OnDeanChanging(value);
					this.SendPropertyChanging();
					this._Dean = value;
					this.SendPropertyChanged("Dean");
					this.OnDeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChancellorAssistant", DbType="Bit")]
		public System.Nullable<bool> ChancellorAssistant
		{
			get
			{
				return this._ChancellorAssistant;
			}
			set
			{
				if ((this._ChancellorAssistant != value))
				{
					this.OnChancellorAssistantChanging(value);
					this.SendPropertyChanging();
					this._ChancellorAssistant = value;
					this.SendPropertyChanged("ChancellorAssistant");
					this.OnChancellorAssistantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViceDean", DbType="Bit")]
		public System.Nullable<bool> ViceDean
		{
			get
			{
				return this._ViceDean;
			}
			set
			{
				if ((this._ViceDean != value))
				{
					this.OnViceDeanChanging(value);
					this.SendPropertyChanging();
					this._ViceDean = value;
					this.SendPropertyChanged("ViceDean");
					this.OnViceDeanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentHead", DbType="Bit")]
		public System.Nullable<bool> DepartmentHead
		{
			get
			{
				return this._DepartmentHead;
			}
			set
			{
				if ((this._DepartmentHead != value))
				{
					this.OnDepartmentHeadChanging(value);
					this.SendPropertyChanging();
					this._DepartmentHead = value;
					this.SendPropertyChanged("DepartmentHead");
					this.OnDepartmentHeadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeanOfficeHead", DbType="Bit")]
		public System.Nullable<bool> DeanOfficeHead
		{
			get
			{
				return this._DeanOfficeHead;
			}
			set
			{
				if ((this._DeanOfficeHead != value))
				{
					this.OnDeanOfficeHeadChanging(value);
					this.SendPropertyChanging();
					this._DeanOfficeHead = value;
					this.SendPropertyChanged("DeanOfficeHead");
					this.OnDeanOfficeHeadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeanAssistant", DbType="Bit")]
		public System.Nullable<bool> DeanAssistant
		{
			get
			{
				return this._DeanAssistant;
			}
			set
			{
				if ((this._DeanAssistant != value))
				{
					this.OnDeanAssistantChanging(value);
					this.SendPropertyChanging();
					this._DeanAssistant = value;
					this.SendPropertyChanged("DeanAssistant");
					this.OnDeanAssistantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchHeadDirect", DbType="Bit")]
		public System.Nullable<bool> BranchHeadDirect
		{
			get
			{
				return this._BranchHeadDirect;
			}
			set
			{
				if ((this._BranchHeadDirect != value))
				{
					this.OnBranchHeadDirectChanging(value);
					this.SendPropertyChanging();
					this._BranchHeadDirect = value;
					this.SendPropertyChanged("BranchHeadDirect");
					this.OnBranchHeadDirectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViceDepartment", DbType="Bit")]
		public System.Nullable<bool> ViceDepartment
		{
			get
			{
				return this._ViceDepartment;
			}
			set
			{
				if ((this._ViceDepartment != value))
				{
					this.OnViceDepartmentChanging(value);
					this.SendPropertyChanging();
					this._ViceDepartment = value;
					this.SendPropertyChanged("ViceDepartment");
					this.OnViceDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchHeadIn", DbType="Bit")]
		public System.Nullable<bool> BranchHeadIn
		{
			get
			{
				return this._BranchHeadIn;
			}
			set
			{
				if ((this._BranchHeadIn != value))
				{
					this.OnBranchHeadInChanging(value);
					this.SendPropertyChanging();
					this._BranchHeadIn = value;
					this.SendPropertyChanged("BranchHeadIn");
					this.OnBranchHeadInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacultyCouncilChief", DbType="Bit")]
		public System.Nullable<bool> FacultyCouncilChief
		{
			get
			{
				return this._FacultyCouncilChief;
			}
			set
			{
				if ((this._FacultyCouncilChief != value))
				{
					this.OnFacultyCouncilChiefChanging(value);
					this.SendPropertyChanging();
					this._FacultyCouncilChief = value;
					this.SendPropertyChanged("FacultyCouncilChief");
					this.OnFacultyCouncilChiefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViceFactCouncilChief", DbType="Bit")]
		public System.Nullable<bool> ViceFactCouncilChief
		{
			get
			{
				return this._ViceFactCouncilChief;
			}
			set
			{
				if ((this._ViceFactCouncilChief != value))
				{
					this.OnViceFactCouncilChiefChanging(value);
					this.SendPropertyChanging();
					this._ViceFactCouncilChief = value;
					this.SendPropertyChanged("ViceFactCouncilChief");
					this.OnViceFactCouncilChiefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Councillors", DbType="Bit")]
		public System.Nullable<bool> Councillors
		{
			get
			{
				return this._Councillors;
			}
			set
			{
				if ((this._Councillors != value))
				{
					this.OnCouncillorsChanging(value);
					this.SendPropertyChanging();
					this._Councillors = value;
					this.SendPropertyChanged("Councillors");
					this.OnCouncillorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secretary", DbType="Bit")]
		public System.Nullable<bool> Secretary
		{
			get
			{
				return this._Secretary;
			}
			set
			{
				if ((this._Secretary != value))
				{
					this.OnSecretaryChanging(value);
					this.SendPropertyChanging();
					this._Secretary = value;
					this.SendPropertyChanged("Secretary");
					this.OnSecretaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacultyBoard", DbType="Bit")]
		public System.Nullable<bool> FacultyBoard
		{
			get
			{
				return this._FacultyBoard;
			}
			set
			{
				if ((this._FacultyBoard != value))
				{
					this.OnFacultyBoardChanging(value);
					this.SendPropertyChanging();
					this._FacultyBoard = value;
					this.SendPropertyChanged("FacultyBoard");
					this.OnFacultyBoardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchBoardCmd", DbType="Int")]
		public System.Nullable<int> BranchBoardCmd
		{
			get
			{
				return this._BranchBoardCmd;
			}
			set
			{
				if ((this._BranchBoardCmd != value))
				{
					this.OnBranchBoardCmdChanging(value);
					this.SendPropertyChanging();
					this._BranchBoardCmd = value;
					this.SendPropertyChanged("BranchBoardCmd");
					this.OnBranchBoardCmdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchBoardRefer", DbType="NVarChar(MAX)")]
		public string BranchBoardRefer
		{
			get
			{
				return this._BranchBoardRefer;
			}
			set
			{
				if ((this._BranchBoardRefer != value))
				{
					this.OnBranchBoardReferChanging(value);
					this.SendPropertyChanging();
					this._BranchBoardRefer = value;
					this.SendPropertyChanged("BranchBoardRefer");
					this.OnBranchBoardReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignmentCmd", DbType="Int")]
		public System.Nullable<int> AssignmentCmd
		{
			get
			{
				return this._AssignmentCmd;
			}
			set
			{
				if ((this._AssignmentCmd != value))
				{
					this.OnAssignmentCmdChanging(value);
					this.SendPropertyChanging();
					this._AssignmentCmd = value;
					this.SendPropertyChanged("AssignmentCmd");
					this.OnAssignmentCmdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignmentRefer", DbType="NVarChar(MAX)")]
		public string AssignmentRefer
		{
			get
			{
				return this._AssignmentRefer;
			}
			set
			{
				if ((this._AssignmentRefer != value))
				{
					this.OnAssignmentReferChanging(value);
					this.SendPropertyChanging();
					this._AssignmentRefer = value;
					this.SendPropertyChanged("AssignmentRefer");
					this.OnAssignmentReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurationID", DbType="Int")]
		public System.Nullable<int> DurationID
		{
			get
			{
				return this._DurationID;
			}
			set
			{
				if ((this._DurationID != value))
				{
					this.OnDurationIDChanging(value);
					this.SendPropertyChanging();
					this._DurationID = value;
					this.SendPropertyChanged("DurationID");
					this.OnDurationIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AcademicService")]
	public partial class AcademicService : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _CommitteeProject;
		
		private string _CommitteeRefer;
		
		private System.Nullable<int> _ExpertInHours;
		
		private string _ExpertInRefer;
		
		private System.Nullable<int> _ExpertInPracHours;
		
		private string _ExpertInPracRefer;
		
		private System.Nullable<int> _ExpertOutHours;
		
		private string _ExpertOutRefer;
		
		private System.Nullable<int> _ExpertOutPracHours;
		
		private string _ExpertOutPracRefer;
		
		private System.Nullable<int> _CommitteeAcPerson;
		
		private string _CommitteeAcRefer;
		
		private System.Nullable<int> _CommitteeCrPerson;
		
		private string _CommitteeCrRefer;
		
		private System.Nullable<int> _CommitteeBsPerson;
		
		private string _CommitteeBsRefer;
		
		private System.Nullable<int> _CommitteeThPerson;
		
		private string _CommitteeThRefer;
		
		private System.Nullable<int> _ServiceAnalysisTimes;
		
		private string _ServiceAnalysisRefer;
		
		private System.Nullable<int> _ServiceOtherTimes;
		
		private string _ServiceOtherRefer;
		
		private System.Nullable<int> _DurationID;
		
		private string _UserName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCommitteeProjectChanging(System.Nullable<int> value);
    partial void OnCommitteeProjectChanged();
    partial void OnCommitteeReferChanging(string value);
    partial void OnCommitteeReferChanged();
    partial void OnExpertInHoursChanging(System.Nullable<int> value);
    partial void OnExpertInHoursChanged();
    partial void OnExpertInReferChanging(string value);
    partial void OnExpertInReferChanged();
    partial void OnExpertInPracHoursChanging(System.Nullable<int> value);
    partial void OnExpertInPracHoursChanged();
    partial void OnExpertInPracReferChanging(string value);
    partial void OnExpertInPracReferChanged();
    partial void OnExpertOutHoursChanging(System.Nullable<int> value);
    partial void OnExpertOutHoursChanged();
    partial void OnExpertOutReferChanging(string value);
    partial void OnExpertOutReferChanged();
    partial void OnExpertOutPracHoursChanging(System.Nullable<int> value);
    partial void OnExpertOutPracHoursChanged();
    partial void OnExpertOutPracReferChanging(string value);
    partial void OnExpertOutPracReferChanged();
    partial void OnCommitteeAcPersonChanging(System.Nullable<int> value);
    partial void OnCommitteeAcPersonChanged();
    partial void OnCommitteeAcReferChanging(string value);
    partial void OnCommitteeAcReferChanged();
    partial void OnCommitteeCrPersonChanging(System.Nullable<int> value);
    partial void OnCommitteeCrPersonChanged();
    partial void OnCommitteeCrReferChanging(string value);
    partial void OnCommitteeCrReferChanged();
    partial void OnCommitteeBsPersonChanging(System.Nullable<int> value);
    partial void OnCommitteeBsPersonChanged();
    partial void OnCommitteeBsReferChanging(string value);
    partial void OnCommitteeBsReferChanged();
    partial void OnCommitteeThPersonChanging(System.Nullable<int> value);
    partial void OnCommitteeThPersonChanged();
    partial void OnCommitteeThReferChanging(string value);
    partial void OnCommitteeThReferChanged();
    partial void OnServiceAnalysisTimesChanging(System.Nullable<int> value);
    partial void OnServiceAnalysisTimesChanged();
    partial void OnServiceAnalysisReferChanging(string value);
    partial void OnServiceAnalysisReferChanged();
    partial void OnServiceOtherTimesChanging(System.Nullable<int> value);
    partial void OnServiceOtherTimesChanged();
    partial void OnServiceOtherReferChanging(string value);
    partial void OnServiceOtherReferChanged();
    partial void OnDurationIDChanging(System.Nullable<int> value);
    partial void OnDurationIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public AcademicService()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeProject", DbType="Int")]
		public System.Nullable<int> CommitteeProject
		{
			get
			{
				return this._CommitteeProject;
			}
			set
			{
				if ((this._CommitteeProject != value))
				{
					this.OnCommitteeProjectChanging(value);
					this.SendPropertyChanging();
					this._CommitteeProject = value;
					this.SendPropertyChanged("CommitteeProject");
					this.OnCommitteeProjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeRefer", DbType="NVarChar(MAX)")]
		public string CommitteeRefer
		{
			get
			{
				return this._CommitteeRefer;
			}
			set
			{
				if ((this._CommitteeRefer != value))
				{
					this.OnCommitteeReferChanging(value);
					this.SendPropertyChanging();
					this._CommitteeRefer = value;
					this.SendPropertyChanged("CommitteeRefer");
					this.OnCommitteeReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpertInHours", DbType="Int")]
		public System.Nullable<int> ExpertInHours
		{
			get
			{
				return this._ExpertInHours;
			}
			set
			{
				if ((this._ExpertInHours != value))
				{
					this.OnExpertInHoursChanging(value);
					this.SendPropertyChanging();
					this._ExpertInHours = value;
					this.SendPropertyChanged("ExpertInHours");
					this.OnExpertInHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpertInRefer", DbType="NVarChar(MAX)")]
		public string ExpertInRefer
		{
			get
			{
				return this._ExpertInRefer;
			}
			set
			{
				if ((this._ExpertInRefer != value))
				{
					this.OnExpertInReferChanging(value);
					this.SendPropertyChanging();
					this._ExpertInRefer = value;
					this.SendPropertyChanged("ExpertInRefer");
					this.OnExpertInReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpertInPracHours", DbType="Int")]
		public System.Nullable<int> ExpertInPracHours
		{
			get
			{
				return this._ExpertInPracHours;
			}
			set
			{
				if ((this._ExpertInPracHours != value))
				{
					this.OnExpertInPracHoursChanging(value);
					this.SendPropertyChanging();
					this._ExpertInPracHours = value;
					this.SendPropertyChanged("ExpertInPracHours");
					this.OnExpertInPracHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpertInPracRefer", DbType="NVarChar(MAX)")]
		public string ExpertInPracRefer
		{
			get
			{
				return this._ExpertInPracRefer;
			}
			set
			{
				if ((this._ExpertInPracRefer != value))
				{
					this.OnExpertInPracReferChanging(value);
					this.SendPropertyChanging();
					this._ExpertInPracRefer = value;
					this.SendPropertyChanged("ExpertInPracRefer");
					this.OnExpertInPracReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpertOutHours", DbType="Int")]
		public System.Nullable<int> ExpertOutHours
		{
			get
			{
				return this._ExpertOutHours;
			}
			set
			{
				if ((this._ExpertOutHours != value))
				{
					this.OnExpertOutHoursChanging(value);
					this.SendPropertyChanging();
					this._ExpertOutHours = value;
					this.SendPropertyChanged("ExpertOutHours");
					this.OnExpertOutHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpertOutRefer", DbType="NVarChar(MAX)")]
		public string ExpertOutRefer
		{
			get
			{
				return this._ExpertOutRefer;
			}
			set
			{
				if ((this._ExpertOutRefer != value))
				{
					this.OnExpertOutReferChanging(value);
					this.SendPropertyChanging();
					this._ExpertOutRefer = value;
					this.SendPropertyChanged("ExpertOutRefer");
					this.OnExpertOutReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpertOutPracHours", DbType="Int")]
		public System.Nullable<int> ExpertOutPracHours
		{
			get
			{
				return this._ExpertOutPracHours;
			}
			set
			{
				if ((this._ExpertOutPracHours != value))
				{
					this.OnExpertOutPracHoursChanging(value);
					this.SendPropertyChanging();
					this._ExpertOutPracHours = value;
					this.SendPropertyChanged("ExpertOutPracHours");
					this.OnExpertOutPracHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpertOutPracRefer", DbType="NVarChar(MAX)")]
		public string ExpertOutPracRefer
		{
			get
			{
				return this._ExpertOutPracRefer;
			}
			set
			{
				if ((this._ExpertOutPracRefer != value))
				{
					this.OnExpertOutPracReferChanging(value);
					this.SendPropertyChanging();
					this._ExpertOutPracRefer = value;
					this.SendPropertyChanged("ExpertOutPracRefer");
					this.OnExpertOutPracReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeAcPerson", DbType="Int")]
		public System.Nullable<int> CommitteeAcPerson
		{
			get
			{
				return this._CommitteeAcPerson;
			}
			set
			{
				if ((this._CommitteeAcPerson != value))
				{
					this.OnCommitteeAcPersonChanging(value);
					this.SendPropertyChanging();
					this._CommitteeAcPerson = value;
					this.SendPropertyChanged("CommitteeAcPerson");
					this.OnCommitteeAcPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeAcRefer", DbType="NVarChar(MAX)")]
		public string CommitteeAcRefer
		{
			get
			{
				return this._CommitteeAcRefer;
			}
			set
			{
				if ((this._CommitteeAcRefer != value))
				{
					this.OnCommitteeAcReferChanging(value);
					this.SendPropertyChanging();
					this._CommitteeAcRefer = value;
					this.SendPropertyChanged("CommitteeAcRefer");
					this.OnCommitteeAcReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeCrPerson", DbType="Int")]
		public System.Nullable<int> CommitteeCrPerson
		{
			get
			{
				return this._CommitteeCrPerson;
			}
			set
			{
				if ((this._CommitteeCrPerson != value))
				{
					this.OnCommitteeCrPersonChanging(value);
					this.SendPropertyChanging();
					this._CommitteeCrPerson = value;
					this.SendPropertyChanged("CommitteeCrPerson");
					this.OnCommitteeCrPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeCrRefer", DbType="NVarChar(MAX)")]
		public string CommitteeCrRefer
		{
			get
			{
				return this._CommitteeCrRefer;
			}
			set
			{
				if ((this._CommitteeCrRefer != value))
				{
					this.OnCommitteeCrReferChanging(value);
					this.SendPropertyChanging();
					this._CommitteeCrRefer = value;
					this.SendPropertyChanged("CommitteeCrRefer");
					this.OnCommitteeCrReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeBsPerson", DbType="Int")]
		public System.Nullable<int> CommitteeBsPerson
		{
			get
			{
				return this._CommitteeBsPerson;
			}
			set
			{
				if ((this._CommitteeBsPerson != value))
				{
					this.OnCommitteeBsPersonChanging(value);
					this.SendPropertyChanging();
					this._CommitteeBsPerson = value;
					this.SendPropertyChanged("CommitteeBsPerson");
					this.OnCommitteeBsPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeBsRefer", DbType="NVarChar(MAX)")]
		public string CommitteeBsRefer
		{
			get
			{
				return this._CommitteeBsRefer;
			}
			set
			{
				if ((this._CommitteeBsRefer != value))
				{
					this.OnCommitteeBsReferChanging(value);
					this.SendPropertyChanging();
					this._CommitteeBsRefer = value;
					this.SendPropertyChanged("CommitteeBsRefer");
					this.OnCommitteeBsReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeThPerson", DbType="Int")]
		public System.Nullable<int> CommitteeThPerson
		{
			get
			{
				return this._CommitteeThPerson;
			}
			set
			{
				if ((this._CommitteeThPerson != value))
				{
					this.OnCommitteeThPersonChanging(value);
					this.SendPropertyChanging();
					this._CommitteeThPerson = value;
					this.SendPropertyChanged("CommitteeThPerson");
					this.OnCommitteeThPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitteeThRefer", DbType="NVarChar(MAX)")]
		public string CommitteeThRefer
		{
			get
			{
				return this._CommitteeThRefer;
			}
			set
			{
				if ((this._CommitteeThRefer != value))
				{
					this.OnCommitteeThReferChanging(value);
					this.SendPropertyChanging();
					this._CommitteeThRefer = value;
					this.SendPropertyChanged("CommitteeThRefer");
					this.OnCommitteeThReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceAnalysisTimes", DbType="Int")]
		public System.Nullable<int> ServiceAnalysisTimes
		{
			get
			{
				return this._ServiceAnalysisTimes;
			}
			set
			{
				if ((this._ServiceAnalysisTimes != value))
				{
					this.OnServiceAnalysisTimesChanging(value);
					this.SendPropertyChanging();
					this._ServiceAnalysisTimes = value;
					this.SendPropertyChanged("ServiceAnalysisTimes");
					this.OnServiceAnalysisTimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceAnalysisRefer", DbType="NVarChar(MAX)")]
		public string ServiceAnalysisRefer
		{
			get
			{
				return this._ServiceAnalysisRefer;
			}
			set
			{
				if ((this._ServiceAnalysisRefer != value))
				{
					this.OnServiceAnalysisReferChanging(value);
					this.SendPropertyChanging();
					this._ServiceAnalysisRefer = value;
					this.SendPropertyChanged("ServiceAnalysisRefer");
					this.OnServiceAnalysisReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceOtherTimes", DbType="Int")]
		public System.Nullable<int> ServiceOtherTimes
		{
			get
			{
				return this._ServiceOtherTimes;
			}
			set
			{
				if ((this._ServiceOtherTimes != value))
				{
					this.OnServiceOtherTimesChanging(value);
					this.SendPropertyChanging();
					this._ServiceOtherTimes = value;
					this.SendPropertyChanged("ServiceOtherTimes");
					this.OnServiceOtherTimesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceOtherRefer", DbType="NVarChar(MAX)")]
		public string ServiceOtherRefer
		{
			get
			{
				return this._ServiceOtherRefer;
			}
			set
			{
				if ((this._ServiceOtherRefer != value))
				{
					this.OnServiceOtherReferChanging(value);
					this.SendPropertyChanging();
					this._ServiceOtherRefer = value;
					this.SendPropertyChanged("ServiceOtherRefer");
					this.OnServiceOtherReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurationID", DbType="Int")]
		public System.Nullable<int> DurationID
		{
			get
			{
				return this._DurationID;
			}
			set
			{
				if ((this._DurationID != value))
				{
					this.OnDurationIDChanging(value);
					this.SendPropertyChanging();
					this._DurationID = value;
					this.SendPropertyChanged("DurationID");
					this.OnDurationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Research")]
	public partial class Research : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ResName;
		
		private System.Nullable<int> _RoundID;
		
		private string _Refer;
		
		private System.Nullable<int> _ProfessorStatusID;
		
		private System.Nullable<int> _Percentage;
		
		private string _UserName;
		
		private System.Nullable<int> _DurationID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnResNameChanging(string value);
    partial void OnResNameChanged();
    partial void OnRoundIDChanging(System.Nullable<int> value);
    partial void OnRoundIDChanged();
    partial void OnReferChanging(string value);
    partial void OnReferChanged();
    partial void OnProfessorStatusIDChanging(System.Nullable<int> value);
    partial void OnProfessorStatusIDChanged();
    partial void OnPercentageChanging(System.Nullable<int> value);
    partial void OnPercentageChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnDurationIDChanging(System.Nullable<int> value);
    partial void OnDurationIDChanged();
    #endregion
		
		public Research()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResName", DbType="NVarChar(150)")]
		public string ResName
		{
			get
			{
				return this._ResName;
			}
			set
			{
				if ((this._ResName != value))
				{
					this.OnResNameChanging(value);
					this.SendPropertyChanging();
					this._ResName = value;
					this.SendPropertyChanged("ResName");
					this.OnResNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundID", DbType="Int")]
		public System.Nullable<int> RoundID
		{
			get
			{
				return this._RoundID;
			}
			set
			{
				if ((this._RoundID != value))
				{
					this.OnRoundIDChanging(value);
					this.SendPropertyChanging();
					this._RoundID = value;
					this.SendPropertyChanged("RoundID");
					this.OnRoundIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Refer", DbType="NVarChar(MAX)")]
		public string Refer
		{
			get
			{
				return this._Refer;
			}
			set
			{
				if ((this._Refer != value))
				{
					this.OnReferChanging(value);
					this.SendPropertyChanging();
					this._Refer = value;
					this.SendPropertyChanged("Refer");
					this.OnReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessorStatusID", DbType="Int")]
		public System.Nullable<int> ProfessorStatusID
		{
			get
			{
				return this._ProfessorStatusID;
			}
			set
			{
				if ((this._ProfessorStatusID != value))
				{
					this.OnProfessorStatusIDChanging(value);
					this.SendPropertyChanging();
					this._ProfessorStatusID = value;
					this.SendPropertyChanged("ProfessorStatusID");
					this.OnProfessorStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percentage", DbType="Int")]
		public System.Nullable<int> Percentage
		{
			get
			{
				return this._Percentage;
			}
			set
			{
				if ((this._Percentage != value))
				{
					this.OnPercentageChanging(value);
					this.SendPropertyChanging();
					this._Percentage = value;
					this.SendPropertyChanged("Percentage");
					this.OnPercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurationID", DbType="Int")]
		public System.Nullable<int> DurationID
		{
			get
			{
				return this._DurationID;
			}
			set
			{
				if ((this._DurationID != value))
				{
					this.OnDurationIDChanging(value);
					this.SendPropertyChanging();
					this._DurationID = value;
					this.SendPropertyChanged("DurationID");
					this.OnDurationIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Supervision")]
	public partial class Supervision : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _StdNumber;
		
		private string _Refer;
		
		private string _UserName;
		
		private System.Nullable<int> _DurationID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnStdNumberChanging(System.Nullable<int> value);
    partial void OnStdNumberChanged();
    partial void OnReferChanging(string value);
    partial void OnReferChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnDurationIDChanging(System.Nullable<int> value);
    partial void OnDurationIDChanged();
    #endregion
		
		public Supervision()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdNumber", DbType="Int")]
		public System.Nullable<int> StdNumber
		{
			get
			{
				return this._StdNumber;
			}
			set
			{
				if ((this._StdNumber != value))
				{
					this.OnStdNumberChanging(value);
					this.SendPropertyChanging();
					this._StdNumber = value;
					this.SendPropertyChanged("StdNumber");
					this.OnStdNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Refer", DbType="NVarChar(MAX)")]
		public string Refer
		{
			get
			{
				return this._Refer;
			}
			set
			{
				if ((this._Refer != value))
				{
					this.OnReferChanging(value);
					this.SendPropertyChanging();
					this._Refer = value;
					this.SendPropertyChanged("Refer");
					this.OnReferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurationID", DbType="Int")]
		public System.Nullable<int> DurationID
		{
			get
			{
				return this._DurationID;
			}
			set
			{
				if ((this._DurationID != value))
				{
					this.OnDurationIDChanging(value);
					this.SendPropertyChanging();
					this._DurationID = value;
					this.SendPropertyChanged("DurationID");
					this.OnDurationIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
